// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/whitekid/go-todo/client (interfaces: Interface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	client "github.com/whitekid/go-todo/client"
	reflect "reflect"
)

// MockInterface is a mock of Interface interface
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// TodoService mocks base method
func (m *MockInterface) TodoService() client.TodoService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TodoService")
	ret0, _ := ret[0].(client.TodoService)
	return ret0
}

// TodoService indicates an expected call of TodoService
func (mr *MockInterfaceMockRecorder) TodoService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TodoService", reflect.TypeOf((*MockInterface)(nil).TodoService))
}
