basePath: /
definitions:
  todo.todoItem:
    properties:
      due_date:
        example: "2006-01-02"
        format: date
        type: string
      id:
        example: 628b92ab-6d95-4fbe-b7c6-09cf5cd8941c
        format: uuid
        type: string
      rank:
        example: 1
        format: int
        type: integer
      title:
        example: do something in future
        type: string
    type: object
info:
  contact: {}
  description: This is a simple todo API service.
  license: {}
  title: TODO API
  version: "1.0"
paths:
  /:
    get:
      description: list todo item
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: list todo item
      tags:
      - todo
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: todo item
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/todo.todoItem'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: create todo item
      tags:
      - todo
  /{item_id}:
    delete:
      description: delete todo item
      parameters:
      - description: todo item ID
        in: path
        name: item_id
        required: true
        type: string
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: delete todo item
      tags:
      - todo
    get:
      description: get todo item
      parameters:
      - description: todo item ID
        in: path
        name: item_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: get todo item
      tags:
      - todo
    put:
      description: update todo item
      parameters:
      - description: todo item ID
        in: path
        name: item_id
        required: true
        type: string
      - description: todo item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/todo.todoItem'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: update todo item
      tags:
      - todo
swagger: "2.0"
